name: HodgePodge
version: 1.1.0
authors: [FEST_Channel, EvilGeniys]

description: Hodgepodge of ideas. We are trying to improve Minecraft gameplay or make the game more convenient.
website: https://github.com/festino/hodgepodge

main: com.festp.Main

commands:
         hodge:
           description: Allows to reload config, get plugin info.
         item:
           description: Give enchanted/renamed item. Simple convenient /give.
           default: op
api-version: 1.14